config/routes.rb
Rails.application.routes.draw do

  resources :main_categories do
    resources :sub_categories do
    end
  end
  
  resources :sub_categories, only: [:show] do
    resources :items
  end
    devise_for :users
   resources :users #, only: [:update]

  resources :items do
    resources :charges
  end
  
    resources :items do
    resources :pal_purcheses
      end
  resources :pal_purcheses do
    post 'creatBuy'#, on: :member
end

  

  
 resources :charges 

  resources :users do
    resources :purchases
  end
  
  resources :items do
    resources :item_pics
  end
  
  get 'about' => 'welcome#about'
  
  root to: 'main_categories#index'

end

app/models/main_category.rb
class MainCategory < ActiveRecord::Base
  has_many :sub_categories, dependent: :destroy
end

app/controllers/main_categories_controller.rb
class MainCategoriesController < ApplicationController
  def index
    @mcategories = MainCategory.all
    
  end

  def show
    @mcategory = MainCategory.find(params[:id])
  end

  def new
    @mcategory = MainCategory.new
  end
  
     def create
       @mcategory = MainCategory.new(params.require(:main_category).permit(:title, :body))
       if @mcategory.save
         flash[:notice] = "Category was saved."
         redirect_to root_path
     else
         flash[:error] = "There was an error saving the Category. Please try again."
       render :new
     end
   end


  def edit
    @mcategory = MainCategory.find(params[:id])
    
  end
  
     def update
       @mcategory = MainCategory.find(params[:id])
       if @mcategory.update_attributes(params.require(:main_category).permit(:title, :body))
         flash[:notice] = "Category was updated."
       redirect_to root_path
     else
         flash[:error] = "There was an error saving the category. Please try again."
       render :edit
     end
   end
  
  
     def destroy
       @mcategory = MainCategory.find(params[:id])
       name = @mcategory.title
 
   
       if @mcategory.destroy
       flash[:notice] = "\"#{name}\" was deleted successfully."
       redirect_to root_path
     else
         flash[:error] = "There was an error deleting the category."
       render :show
     end
   end


  
end

app/helpers/main_categories_helper.rb
module MainCategoriesHelper
end

app/views/main_categories/edit.html.erb
 <h1>Edit Main Category</h1>
 
 <div class="row">
   <div class="col-md-4" style="dispay:block;">
     <p>Guidelines : none</p>

   </div>
   <div class="col-md-8">
     <%= form_for @mcategory do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
         <%= link_to "Delete Category", @mcategory, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this category?' } %> 
       </div>
     <% end %>
   </div>
 </div>
<center style="margin-top:50px; margin-bottom:100px;">
  <h2>Sub Categories Edit</h2>
  <p  style="margin-bottom:50px" ><%=link_to "New sub-category", new_main_category_sub_category_path(@mcategory.id) ,class: 'btn btn-success'%></p>
<%@mcategory.sub_categories.each do |sub|%>
  <p><%=link_to sub.title, edit_main_category_sub_category_path(@mcategory.id, sub.id)   %></p>
  
        <%if sub.avatar.url  %>
             <img src="<%= sub.avatar.url %>"  width="42" height="42"> 
        <%end%>
  <%end%>
  
</center>

app/views/main_categories/index.html.erb
  <div style="display:box; background-color:#F5F5F5; 
             padding-bottom:400px; padding-top:60px;
            border-radius: 25px; margin-left: auto;
    			  margin-right: auto;	
    			  width: 100%;
">
<div class="head2">
<center><h1 class="top-op">Git-This.Com</h1><br/><h3 style="color:grey; font-family: Comic Sans MS; ">PDFBooks Relm</h3>
  </center>
<!--  <p class="top-op" style="float:left; margin-top:10px; margin-left:16px;"><%= link_to "Options", '#' %></p> -->
  <%if current_user and current_user.role =="admin"%>
          <p class="top-op" style="float:right;  margin-top:10px; margin-left:16px;"> <%= link_to "New", new_main_category_path %> </p>
  <%elsif current_user%>
          <p class="top-op" style="float:right;  margin-top:10px; margin-left:16px; margin-right:10px;"> <%= link_to "Purchases", user_purchases_path(current_user.id) %> </p>
  <%end%>
</div> 
    
    
<div class="div1" >
 
   <%a = []%>
  <%MainCategory.all.each do |num| %>
  <% a << num.id   %>
  <%end%><br/>
  
  <% m3 = a.length / 3 -1 %>
  <% ab = a[0..a.length / 3 - 1]%>
  <% b = a[m3+1..m3*2+1]%>
  <% c = a[m3*2+2..m3*3+2]%>
  
<%    %>

  <div class="row" style="margin-left:auto; margin-right:auto; width:100%;">
          <div class="col-md-4">

            <% MainCategory.find(ab).each do |cat| %>
                        <%if current_user and current_user.role == "admin"%>
                              <p class="main"><%=link_to cat.title, main_category_path(cat.id) %><%=link_to "admin", edit_main_category_path(cat.id)%></p>
                        <%else%>
                             <p class="main"><%=link_to cat.title,main_category_path(cat.id) %></p>
                        <%end%>

                              <%cat.sub_categories.each do |scat| %>
                                                                <p class='sub' style=""><%# scat.avatar.url ? image_tag( scat.avatar.url ) : "" %>
                                                        <table style="width:100%">
                                                                <tr> 
                                                            <%if scat.avatar.url%>
                                                                
                                                                     <td> <img src="<%= scat.avatar.url %>"  width="42" height="42">
                                                            <%end%>
                                                                      <td> <%=link_to scat.title, scat %>
                                                                 </tr>
                                                          </table>              
                                                                    </p>
                                                               
                                                      <%end%>
                      <% end   %>
           </div>
          
    
          <div class="col-md-4">
 

                    <% MainCategory.find(b).each do |cat| %>
                        <%if current_user and current_user.role == "admin"%>
                              <p class="main"><%=link_to cat.title, main_category_path(cat.id) %><%=link_to "Admin", edit_main_category_path(cat.id)%></p>
                        <%else%>
                             <p class="main"><%=link_to cat.title,main_category_path(cat.id) %></p>
                        <%end%>

                              <%cat.sub_categories.each do |scat| %>
                                                                <p class='sub' style=""><%# scat.avatar.url ? image_tag( scat.avatar.url ) : "" %>
                                                        <table style="width:100%">
                                                                <tr> 
                                                            <%if scat.avatar.url%>
                                                                
                                                                     <td> <img src="<%= scat.avatar.url %>"  width="42" height="42">
                                                            <%end%>
                                                                      <td> <%=link_to scat.title, scat %>
                                                                 </tr>
                                                          </table>              
                                                                    </p>
                                                               
                                                      <%end%>
                    <% end   %>
           </div>
           <div class="col-md-4">
 

                    <% MainCategory.find(c).each do |cat| %>
                        <%if current_user and current_user.role == "admin"%>
                              <p class="main"><%=link_to cat.title, main_category_path(cat.id) %><%=link_to "Admin", edit_main_category_path(cat.id)%></p>
                        <%else%>
                             <p class="main"><%=link_to cat.title,main_category_path(cat.id) %></p>
                        <%end%>

                              <%cat.sub_categories.each do |scat| %>
                                                                <p class='sub' style=""><%# scat.avatar.url ? image_tag( scat.avatar.url ) : "" %>
                                                        <table style="width:100%">
                                                                <tr> 
                                                            <%if scat.avatar.url%>
                                                                
                                                                     <td> <img src="<%= scat.avatar.url %>"  width="42" height="42">
                                                            <%end%>
                                                                      <td> <%=link_to scat.title, scat %>
                                                                 </tr>
                                                          </table>              
                                                                    </p>
                                                               
                                                      <%end%>
                    <% end   %>
           </div>

</div> 
       </div> 




    </div>

 
  
  
  
  

app/views/main_categories/new.html.erb
<%= form_for @mcategory do |f| %>
   <%= f.label :title %>
   <%= f.text_field :title %>
 
   <%= f.label :body %>
   <%= f.text_area :body %>
   <%= f.submit "Save" %>
 <% end %>

<!-- ===================================================================================================================== -->

app/views/main_categories/show.html.erb
<div style="display:box; background-color:#F5F5F5;
            margin-left:auto; margin-right:auto;
            width:90%; padding-bottom:400px;
            padding-top:60px; border-radius: 25px; ">
<h1 style="padding-left:30px;"><%= @mcategory.title %></h1>
  
 <div style="padding-left:50px;"> 
<%@mcategory.sub_categories.each do |test|%>
    <% test.items.each do |item| %>
          <p> 
            <% if item.item_pics.first %>
           <img src="<%= item.item_pics.first.avatar.url %>"  width="42" height="42"> 
            <% end %>                          
            <%=link_to item.name, sub_category_item_path(item.sub_category_id, item.id)%>
            
          </p>
    <%end%>
<%end%>
  </div>
</div>