config/routes.rb
Rails.application.routes.draw do

  resources :main_categories do
    resources :sub_categories do
    end
  end
  
  resources :sub_categories, only: [:show] do
    resources :items
  end
    devise_for :users
   resources :users #, only: [:update]

  resources :items do
    resources :charges
  end
  
    resources :items do
    resources :pal_purcheses
      end
  resources :pal_purcheses do
    post 'creatBuy'#, on: :member
end

  

  
 resources :charges 

  resources :users do
    resources :purchases
  end
  
  resources :items do
    resources :item_pics
  end
  
  get 'about' => 'welcome#about'
  
  root to: 'main_categories#index'

end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
  belongs_to :main_category
  has_many :items, dependent: :destroy
  mount_uploader :avatar, AvatarUploader
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  def index
    @scategories = SubCategory.all
  end

  def show
      @scategory = SubCategory.find(params[:id])
  end

  def new
    @mcategory= MainCategory.find(params[:main_category_id])
    @scategory = SubCategory.new
  end
  
    
     def create
       #@scategorymid =Subcategory.find(params[:main_category_id])
       @mcategory= MainCategory.find(params[:main_category_id])
       @scategory = @mcategory.sub_categories.build(params.require(:sub_category).permit(:title, :body, :avatar))
      # @scategory.main_category_id = @mcategory.id
       if @scategory.save
         flash[:notice] = "Category was saved."
       
        redirect_to edit_main_category_path(@mcategory.id)
       
     else
         flash[:error] = "There was an error saving the Category. Please try again."
       render :new
     end
     end

  def edit
    @mcategory= MainCategory.find(params[:main_category_id])
    @scategory = SubCategory.find(params[:id])
  end
  
    
     def update
        @mcategory= MainCategory.find(params[:main_category_id])
       @scategory = SubCategory.find(params[:id])
       if @scategory.update_attributes(params.require(:sub_category).permit(:title, :body, :avatar))
         flash[:notice] = "Category was updated."
       redirect_to edit_main_category_path(@mcategory.id)
     else
         flash[:error] = "There was an error saving the category. Please try again."
       render :edit
     end
     end
  
       def destroy
       @mcategory= MainCategory.find(params[:main_category_id])
       @scategory = SubCategory.find(params[:id])
       name = @scategory.title
 
   
       if @scategory.destroy
       flash[:notice] = "\"#{name}\" was deleted successfully."
       #redirect_to root_path
       redirect_to edit_main_category_path(@mcategory.id)
     else
         flash[:error] = "There was an error deleting the category."
       render :show
     end
       end
  
  
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/views/sub_categories/edit.html.erb
 <h1>Edit Sub Category</h1>
 
 <div class="row">
   <div class="col-md-4" style="dispay:block;">
     <p>Guidelines : none</p>

   </div>
   <div class="col-md-8">
     <%= form_for [@mcategory, @scategory] do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter category title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter category body" %>
       </div>
    
     <%= image_tag( @scategory.avatar.url ) %>
        <div class="form-group">
         <%= f.label :avatar %>
         <%= f.file_field :avatar %>
         <%= f.hidden_field :avatar_cache %>
       </div>

       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
         <%= link_to "Delete Category", [@mcategory, @scategory], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this category?' } %> 
       </div>
     <% end %>
   </div>
 </div>

app/views/sub_categories/index.html.erb
<h1>SubCategories#index</h1>
<p>Find me in app/views/sub_categories/index.html.erb</p>

app/views/sub_categories/new.html.erb
<%= form_for [@mcategory, @scategory] do |f| %>
   <%= f.label :title %>
   <%= f.text_field :title %>
 
   <%= f.label :body %>
   <%= f.text_area :body %>
 
   <%= f.submit "Save" %>
 <% end %>

app/views/sub_categories/show.html.erb
<div style="display:box; background-color:#F5F5F5;
            margin-left:auto; margin-right:auto;
            width:90%; padding-bottom:400px;
            padding-top:60px; border-radius: 25px; ">
    <div style="padding-left:60px;">
<h1 style="color: lightgrey"><%= @scategory.main_category.title %></h1>
      
    
<h2><%=@scategory.title%></h2>
       <div style="padding-left:20%;"> 
  <%if current_user%>
        <% if current_user %>
            <p><button><%=link_to "Post Item Here", new_sub_category_item_path(@scategory.id)%></button></p>
        <%end%>
  <%end%>
<% @scategory.items.each do |item|%>
<p style="color:red;">
  <% if item.item_pics.length >= 1 %>
    <img src="<%= item.item_pics.last.avatar.url %>"  width="42" height="42">
  <%# item.item_pics.length %>
  <%end%>
  <%=link_to item.name, sub_category_item_path( @scategory.id, item.id )  %>
</p>
<% end%>
   </div>   
      
</div>
    </div>
  