config/routes.rb
Rails.application.routes.draw do

  resources :main_categories do
    resources :sub_categories do
    end
  end
  
  resources :sub_categories, only: [:show] do
    resources :items
  end
    devise_for :users
   resources :users #, only: [:update]

  resources :items do
    resources :charges
  end
  
    resources :items do
    resources :pal_purcheses
      end
  resources :pal_purcheses do
    post 'creatBuy'#, on: :member
end

  

  
 resources :charges 

  resources :users do
    resources :purchases
  end
  
  resources :items do
    resources :item_pics
  end
  
  get 'about' => 'welcome#about'
  
  root to: 'main_categories#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :sub_category
  belongs_to :user
  has_many :item_pics, dependent: :destroy
  mount_uploader :avatar, AvatarUploader
  mount_uploader :product, ProductUploader
  
  #validates :product, inclusion: { in: %w( pdf ),
   # message: "%{value} is not a valid format" }
  
end

app/controllers/items_controller.rb
require 'open-uri'

class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
    @purchase = Purchase.new
    respond_to do |format|
      format.html
      format.pdf { 
        #data = open @item.avatar.url, "r"
        #send_data data, type: "application/pdf", disposition: "attachment", :filename => @item.avatar.file.filename }
        
        #data = open @item.product.url, "r"
        #send_data data, type: "application/pdf", disposition: "attachment", :filename => @item.product.file.filename, x_sendfile: true }
      
      
        open(@item.product.url, 'rb') do |f|
          send_data f.read.force_encoding('BINARY'), filename: @item.product.file.filename, type: 'application/pdf', disposition: 'attachment'
        end
      }
    end

  end

  def new
    @scategory = SubCategory.find(params[:sub_category_id])
    @item = Item.new
  end
  
     def create
     
       @scategory= SubCategory.find(params[:sub_category_id])
       @item = @scategory.items.build(params.require(:item).permit(:name, :body, :avatar, :product, :price ))
      
       if @item.save
         #@item.update_attribute!(user_id: current_user.id)
         Item.where(id: @item.id).update_all(user_id: current_user.id)
         flash[:notice] = "Item was saved. "
         redirect_to  new_item_item_pic_path(@item.id)
        # redirect_to sub_category_path(@scategory)
       
     else
         flash[:error] = "There was an error saving the Item. Please try again."
       render :new
     end
   end
  

  def edit
    
    #@mcategory = MainCategory.find(params[:main_category_id])
    @scategory = SubCategory.find(params[:sub_category_id])
    @item = Item.find(params[:id])
    @item_pic = ItemPic.new
  end
  
    def update
       # @mcategory= MainCategory.find(params[:main_category_id])
      @scategory = SubCategory.find(params[:sub_category_id])
      @item = Item.find(params[:id])
      if @item.update_attributes(params.require(:item).permit(:name, :body, :avatar, :price, :product))
        flash[:notice] = "Item was updated."
        redirect_to sub_category_item_path(@scategory, @item)
     else
        flash[:error] = "There was an error saving the item. Please try again."
        # render :edit
        redirect_to edit_sub_category_item_path(@scategory, @item)
     end
   end
  
    def destroy
          # @mcategory= MainCategory.find(params[:main_category_id])
           @scategory = SubCategory.find(params[:sub_category_id])
           @item = Item.find(params[:id])
           name = @item.name
 
   
           if @item.destroy
       flash[:notice] = "\"#{name}\" was deleted successfully."
       #redirect_to root_path
       redirect_to sub_category_path(@scategory)
     else
             flash[:error] = "There was an error deleting the Item."
       render :show
     end
   end
  
  
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<script>
        function validateForm() {
                                    var x = document.forms["editItem"]["item_product"].value;
                                    
          
                                      if (x == null || x == "") {
                                                                   
                                                                    return true;
                                                                }
          
                                    else if ( x.slice(-3) !== "pdf"  ) { 
                                                                          alert("Book must be in  pdf format");
                                                                          return false;
                                                                        }
                                }
</script>
 <h1>Edit Item</h1>
 
 <div class="row">
   <div class="col-md-4" style="dispay:block;">
     <p>Guidelines : none</p>

   </div>
   <div class="col-md-8">
     <%= form_for [@scategory, @item], :html => { :onsubmit => 'return validateForm()', :name => 'editItem' } do |f| %>
       <div class="form-group">
         <%= f.label :name %>
         <%= f.text_field :name, class: 'form-control', placeholder: "Enter Item name" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter category body"  %>
       </div>
    
        <div class="form-group">
          <%= f.label :price %>
          <%= f.text_area :price, rows: 1, class: 'form-control', placeholder: "price" %>
       </div>
     
     <%# image_tag( @item.avatar.url ) %>
    <div class="form-group">
         <%# f.label "Product" %>
         <%# f.file_field :avatar %>
         <%# f.hidden_field :avatar_cache %>
   </div>
   
    <div class="form-group">
      <%= f.label "Product" %>
      <%= f.file_field :product %>
      <%= f.hidden_field :product_cache %>
   </div>

       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
         <%= link_to "Delete Item", [@scategory, @item] , method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this category?' } %> 
       </div>
     <% end %>
   <% @item.item_pics.each do |pic|%>
   <div style="display:inline;">
     <%=link_to image_tag(pic.avatar.url, size: "50"), edit_item_item_pic_path(@item.id, pic.id) %>
     </div>
   <%end%>
   
    <%= render 'item_pics/newpics' %>
   
   </div>

app/views/items/index.html.erb
<h1>Items#index</h1>

<%@items.each do |item|%>
<p><%=item.name%></p>
<%end%>

app/views/items/new.html.erb
<script>
        function validateForm() {
                                    var x = document.forms["new_item"]["item_product"].value;
          
                                    if (x.slice(-3) !== "pdf") {
                                                                alert("must choose a pdf book");
                                                                return false;
                                                                }
                                }
</script>
<h1>Post Item</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for posts</p>
     <ul>
       <li>Nmone Yet!</li>
  
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for [ @scategory, @item ], :html => { :onsubmit => 'return validateForm()'} do |f| %>
       <div class="form-group">
         <%= f.label :name %>
         <%= f.text_field :name, class: 'form-control', placeholder: "Enter item title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter item description" %>
       </div>
     
        <div class="form-group">
          <%= f.label :price %>
          <%= f.text_field :price, class: 'form-control', placeholder: "Enter item price" %>
       </div>
     
        <div class="form-group">
         <%# f.label "Product" %>
         <%# f.file_field :avatar %>
         <%# f.hidden_field :avatar_cache %>
       </div>
     
     
       <div class="form-group">
              <%= f.label "Product" %>
              <%= f.file_field :product %>
              <%= f.hidden_field :product_cache %>
          
       </div>
     
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
   
     <%# render 'item_pics/newpics' %>
   
</div>

app/views/items/show.html.erb
<center style="margin-bottom:100px;">
<div style="display:box; background-color:#F5F5F5; 
            width:90%; padding-bottom:400px; padding-top:60px;
            border-radius: 25px; ">
<h1><%=@item.name%></h1>
  <%if current_user%>
        <% if current_user.role == "admin" || @item.user_id == current_user.id  %>
              <p><button><%=link_to "edit item", edit_sub_category_item_path(@item.sub_category_id, @item.id)%></button></p>
        <%end%>
  <%end%>
  
  <%if @item.item_pics.length >= 1  %>
  
<script>

      var num=1
      <%i=0%>
<% @item.item_pics.each do |pic|%>
          <% n = i+=1%>
      img<%=n%> = new Image ()
      img<%=n%>.src = "<%=pic.avatar.url%>"
<%end%>

function slideshowUp()
					{
					num=num+1
					if (num==5){num=1}
				document.mypic.src=eval("img"+num+".src")
					}

function slideshowBack()
						{
							num=num-1
							if (num==0) {num=4}
							document.mypic.src=eval("img"+num+".src")
						}

</script>

<!-- The Image and Form Codes are Below --> 


<IMG SRC="<%=@item.item_pics.first.avatar.url%>" 
NAME="mypic" width="300" style="margin-bottom:10px;"><br/>





  <a href="JavaScript:slideshowBack()" style="margin-right:20px;"> Back</a><%= "#{@item.item_pics.length}pics" %>

<a href="JavaScript:slideshowUp()" style="margin-left:20px;"> Next</a> 




<%end%>
  <p style="margin-top:20px; padding-right:40px; padding-left:40px;" > <%= @item.body %> </p>
  
  
  <% if current_user %>
  <% match = current_user.purchases.where( Item_id: @item.id ).pluck[0] %>
        <% # if Purchase.where(user_id: current_user.id) %>
         <% if match %>
                <div style="margin-top:100px;">
                <h4>Already Purchased</h4> 
            
                  <!--  <a class='btn btn-success' href="<%=@item.product%>" download >download</a> <br/><br/> -->
                  <%=link_to "download", sub_category_item_path(@item.sub_category_id, @item, format: "pdf"), class: 'btn btn-success'%><br/><br/>
                  <%#link_to "download", @item.product.url , options={download}, class: 'btn btn-success'%><br/><br/>

                 </div> 
            
          <%else%>
                        <%= form_tag item_charges_path(@item.id) do %>
    
                       <article>
                          <label class="amount">
                            <span>  <h3>Git this</h3> <p>Amount: <%= @item.price == nil ? "Free" : "#{@item.price}$" %></p></span>
                          </label>
                        </article>

                        <script src="https://checkout.stripe.com/checkout.js" 
                                class="stripe-button"
                                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                                data-description="<%=@item.name%>"
                                data-amount="<%= @item.price.to_i*100 %>">
                        </script>
                        <% end %>
        <%end%>
  
  <%else%>
  <div style="margin-top:100px; " >
  <p><b>To git this please sign in or sign up</b></p>
    <%=link_to "guest Buy", new_item_pal_purchese_path(@item.id), class: 'btn btn-success' %>
<%=link_to "Sign in", user_session_path , class: 'btn btn-success'  %> or <%=link_to "Sign up", new_user_registration_path , class: 'btn btn-success'  %>
  
  
  <%end%> 
  
  </div>
  </div>
</center>
  